variable "instance_type" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "iam_instance_profile" {}
variable "key_name" {}
variable "monitoring" {}
variable "disable_api_termination" {}
variable "ebs_optimized" {}
variable "private_ip" {}
variable "source_dest_check" {}
variable "additional_eni" {}
variable "additional_eni_device_index" {}
variable "additional_eni_subnet_id" {}
variable "additional_eni_security_groups" {}
variable "create_eni" {}
variable "root_block_device" {}
variable "ebs_block_device" {}
variable "user_data" {}
variable "ami" {}
variable "tags" {}

variable "cluster_identifier" {}
variable "node_type" {}
variable "master_username" {}
variable "master_password" {}
variable "cluster_type" {}
variable "publicly_accessible" {}
variable "skip_final_snapshot" {}
variable "iam_roles" {}
variable "vpc_security_group_ids" {}
variable "cluster_subnet_group_name" {}
variable "encrypted" {}
variable "kms_key_id" {}
variable "deletion_protection" {}
variable "automated_snapshot_retention_period" {}
variable "availability_zone_relocation_enabled" {}
variable "copy_grants" {}
