variable "subnet_id" {}
variable "iam_instance_profile" {}
variable "instance_type" {}
variable "ebs_optimized" {}
variable "monitoring" {}
variable "enable_volume_tags" {}
variable "ami" {}
variable "private_ip" {}
variable "vpc_security_group_ids" {}
variable "user_data" {}
variable "root_block_device" {}
variable "create_eni" {}
variable "eni_delete_on_termination" {}
variable "eni_device_index" {}
variable "eni_security_groups" {}
variable "enable_termination_protection" {}
variable "disable_api_stop" {}
variable "disable_api_termination" {}
variable "tags" {}
